name: service_delivery
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.66.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  flutter_svg: ^2.0.17
  http: ^1.3.0
  image_picker: ^1.0.4
  firebase_storage: 12.4.5
  smooth_page_indicator: ^1.2.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  url_launcher: ^6.0.0


  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

dev_dependencies:
  built_value: ^8.9.5
  built_collection: ^5.1.1
  build_runner: ^2.4.13
  built_value_generator: ^8.9.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter_launcher_icons:
  image_path: "assets/images/logo.png"
  android: "ic_launcher"
  background_color: "#000000"
  ios: "AppIcon"
  min_sdk_android: 21

flutter_native_splash:
  color: "#000000"
  image: "assets/images/images.jpeg"
  android_12:
    image: "assets/images/images.jpg"


flutter:
  uses-material-design: true
  assets:
    - assets/images/