// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Rk2Lb0vbrUku9zLRuZ7UcV1YVzUF-NY',
    appId: '1:1061708838077:web:19322d2f4ed728c17933d4',
    messagingSenderId: '1061708838077',
    projectId: 'service-app-2025',
    authDomain: 'service-app-2025.firebaseapp.com',
    storageBucket: 'service-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOawHgyBxr9VMBJB-Yryfe55bKRnJ668o',
    appId: '1:1061708838077:android:d1dbf856abca6bd37933d4',
    messagingSenderId: '1061708838077',
    projectId: 'service-app-2025',
    storageBucket: 'service-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8VzyMy6eNmGqEr3fo4X1r-0oVAa_zNqI',
    appId: '1:1061708838077:ios:6160b9c73f360f3d7933d4',
    messagingSenderId: '1061708838077',
    projectId: 'service-app-2025',
    storageBucket: 'service-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.serviceDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8VzyMy6eNmGqEr3fo4X1r-0oVAa_zNqI',
    appId: '1:1061708838077:ios:6160b9c73f360f3d7933d4',
    messagingSenderId: '1061708838077',
    projectId: 'service-app-2025',
    storageBucket: 'service-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.serviceDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3Rk2Lb0vbrUku9zLRuZ7UcV1YVzUF-NY',
    appId: '1:1061708838077:web:df35c4485b7c032c7933d4',
    messagingSenderId: '1061708838077',
    projectId: 'service-app-2025',
    authDomain: 'service-app-2025.firebaseapp.com',
    storageBucket: 'service-app-2025.firebasestorage.app',
  );

}